### ISSUE TITLE
cfgs/tesla714.yaml

### ISSUE THREAD

**Issue by Yupeng-mango** [zijianzhang/CARLA_INVS#2]
when I run `python PCDet/INVS_main.py`
there is an error `FileNotFoundError: [Errno 2] No such file or directory: 'cfgs/tesla714.yaml'` 
could you tell me where I can find this file?
Thanks very much!

**Comment by iamhyc** [comment]
> when I run `python PCDet/INVS_main.py`
> there is an error `FileNotFoundError: [Errno 2] No such file or directory: 'cfgs/tesla714.yaml'`
> could you tell me where I can find this file?
> Thanks very much!

hi, llyp0903, thanks for your issue!

~~It seems like the cfg files are not uploaded, wait a minute.~~

The cfg files are now uploaded (54e9ab3).

There may exist other path-related issues cause we have not thoroughly checked this repo.
Please feel free to comment below or create another issue, if you found other questions.

**Comment by Yupeng-mango** [comment]
> > when I run `python PCDet/INVS_main.py`
> > there is an error `FileNotFoundError: [Errno 2] No such file or directory: 'cfgs/tesla714.yaml'`
> > could you tell me where I can find this file?
> > Thanks very much!
> 
> hi, llyp0903, thanks for your issue!
> 
> ~It seems like the cfg files are not uploaded, wait a minute.~
> 
> The cfg files are now uploaded ([54e9ab3](https://github.com/zijianzhang/CARLA_INVS/commit/54e9ab37d3dc42db2258bcf00f46f379c6e504a4)).
> 
> There may exist other path-related issues cause we have not thoroughly checked this repo.
> Please feel free to comment below or create another issue, if you found other questions.

Alright, thank you!
