### ISSUE TITLE
About pytorch and other versions

### ISSUE THREAD

**Issue by s1710335** [zijianzhang/CARLA_INVS#4]
I would like to create the same environment as yours, so please let me know what versions of pytorch and cuda,llvm you have.
Also, is carla available as a downloadable version? (Does it have to be the built one?).

**Comment by iamhyc** [comment]
The required dependencies are listed on the README, and you could also check `Makefile` for more details.

1. As for the exact version number, we originally use:  `torch-1.3.1`, `cuda-10.1`, `llvm-10.0`
2. As for CARLA, you can download it from the [github repo](https://github.com/carla-simulator/carla/releases)
