### ISSUE TITLE
Outdated sample dataset link

### ISSUE THREAD

**Issue by JinghaoZhao** [zijianzhang/CARLA_INVS#9]
Hello, it seems that the download link for the sample dataset is outdated (https://cloud.189.cn/web/share?code=jQJvuimquaEj) Are there any other links available? Thanks a lot!

**Comment by bearswang** [comment]
Hi Jinghao, you may refer to INVS 2.0 (i.e., CarlaFLCAV) at: https://github.com/SIAT-INVS/CarlaFLCAV. It provides some example data.

**Comment by JinghaoZhao** [comment]
Thanks!
